replicaCount: 2

image:
  repository: ghcr.io/paulodhiambo/zia-portal
  pullPolicy: IfNotPresent
  tag: 9782c01

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: true
  baseDomain: cluster.lakesideinn.space
  auth:
    enabled: false

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
